package:
  name: cil
  version: {{ environ['CIL_VERSION'] }}

build:
  skip: True # [py==38 and np==115]
  preserve_egg_dir: False
  script_env:
    - CIL_VERSION   
  #number: 0  
  missing_dso_whitelist:
    - /lib64/libc.so.6            # [linux]
    - /lib64/libm.so.6            # [linux]
    - /lib64/libpthread.so.0      # [linux]
    - /lib64/ld-linux-x86-64.so.2 # [linux]

test:
  requires:
    - {{ pin_compatible('numpy', min_pin='x.x', max_pin='x.x') }}
    - python-wget
    - cvxpy # [ unix and py36 and np115 ]
    - scikit-image  
    - tomophantom # [ unix ]
    - cil-astra # [ unix ] 
    - tigre
    - numba
    - packaging
    - ccpi-regulariser
    
  source_files:
    - ./Wrappers/Python/test     # [win]
    - ./cil/Wrappers/Python/test # [not win] 

  commands:
    - python -c "import os; print ('TESTING IN THIS DIRECTORY' , os.getcwd())"
    - python -m unittest discover Wrappers/Python/test        # [win]
    - python -m unittest discover -s cil/Wrappers/Python/test # [not win]
    
requirements:
  build:
    - python
    - numpy {{ numpy }}
    - setuptools
    - cmake
    - libgcc-ng     # [linux]
    - libstdcxx-ng  # [linux]
    - _openmp_mutex # [linux]
    - openmp        # [osx]
    - vc 14         # [win]

  run:
    - python
    - {{ pin_compatible('numpy', min_pin='x.x', max_pin='x.x') }}
    - scipy
    - matplotlib
    - h5py
    - pillow
    - libgcc-ng     # [linux]
    - libstdcxx-ng  # [linux]
    - _openmp_mutex # [linux]
    - openmp        # [osx]
    - vc 14         # [win]
    - dxchange
    - olefile >=0.46
    - pywavelets
    
  
about:
  home: http://www.ccpi.ac.uk/cil
  license:  Apache 2.0 License
  summary: 'CCPi Core Imaging Library'
