package:
  name: cil
  version: {{ environ.get('GIT_DESCRIBE_TAG','v')[1:].split('-')[0] }}

source:
  path: ..

build:
  preserve_egg_dir: False
  number: {{ GIT_DESCRIBE_NUMBER }}
  missing_dso_whitelist:
    - /lib64/libc.so.6            # [linux]
    - /lib64/libm.so.6            # [linux]
    - /lib64/libpthread.so.0      # [linux]
    - /lib64/ld-linux-x86-64.so.2 # [linux]

test:
  requires:
    - python-wget
    - cvxpy                   # [linux]
    - scikit-image
    - tomophantom=2.0.0       # [linux]
    - tigre=2.6
    - packaging
    - ccpi-regulariser=24.0.1 # [not osx]
    - astra-toolbox=2.1=cuda* # [not osx]
    - matplotlib-base >=3.3.0

  source_files:
    - ./Wrappers/Python/test

  commands:
    - pip install unittest-parametrize
    - python -m unittest discover -v -s Wrappers/Python/test  # [win]
    - python -m unittest discover -s Wrappers/Python/test -v  # [not win]
    

requirements:
  build:
    - python
    - numpy {{ numpy }}
    - pip
    - setuptools >=64
    - setuptools_scm >=8
    - cmake >=3.20
    - libgcc-ng     # [linux]
    - libstdcxx-ng  # [linux]
    - _openmp_mutex # [linux]
    - openmp        # [osx]
    - vc 14         # [win]
    - ipp-include {{ ipp_version }} 
    - ipp-devel {{ ipp_version }} 
    - ipp {{ ipp_version }} 

  run:
    - python
    - {{ pin_compatible('numpy', min_pin='x.x', max_pin='x.x') }}
    - scipy >=1.4.0
    - h5py
    - pillow
    - libgcc-ng     # [linux]
    - libstdcxx-ng  # [linux]
    - _openmp_mutex # [linux]
    - openmp        # [osx]
    - vc 14         # [win]
    - dxchange
    - olefile >=0.46
    - pywavelets
    - cil-data >=22
    - {{ pin_compatible('ipp', min_pin='x.x', max_pin='x.x') }}
    - tqdm
    - numba
    - zenodo_get >=1.6

  #optional packages with version dependancies
  run_constrained:
    - tomophantom=2.0.0
    - astra-toolbox>=1.9.9.dev5,<=2.1
    - tigre>=2.4,<=2.6
    - ccpi-regulariser=24.0.1
    - ipywidgets

about:
  home: https://TomographicImaging.github.io/CIL
  license:  Apache 2.0 License
  summary: 'CCPi Core Imaging Library'
