package:
  name: cil
  version: {{ environ.get('GIT_DESCRIBE_TAG','v')[1:].split('-')[0] }}

source:
  path: ..

build:
  preserve_egg_dir: False
  number: {{ GIT_DESCRIBE_NUMBER }}

test:
  requires:
    - pip
    - python-wget
    - cvxpy                   # [linux]
    - scikit-image
    - tomophantom 2.0.0       # [linux]
    - tigre 2.6
    - packaging
    - ccpi-regulariser 24.0.1 # [not osx]
    - astra-toolbox 2.1 {{ 'cuda*' if environ.get('TESTS_FORCE_GPU', '') else 'py*' }}
    - matplotlib-base >=3.3
    - zenodo_get >=1.6
    - dxchange >= 0.2.1
    - olefile >=0.46

  source_files:
    - ./Wrappers/Python/test

  commands:
    - pip install unittest-parametrize
    - python -m unittest discover -v -s Wrappers/Python/test

{% set ipp_version = '2021.12' %}

requirements:
  build:
    - cmake >=3.16
    - ninja
    - {{ compiler('cxx') }}

  host:
    - libgomp      # [linux]
    - llvm-openmp  # [osx]
    - ipp-include {{ ipp_version }}
    - ipp-devel {{ ipp_version }}
    - python x.x
    - pip
    - setuptools >=64
    - setuptools_scm >=8
    - scikit-build-core >=0.10

  run:
    - {{ pin_compatible('python', min_pin='x.x') }}
    - ipp {{ ipp_version }}
    - numpy >=1.23,<2
    - scipy >=1.4
    - h5py
    - pillow
    - pywavelets
    - cil-data >=22
    - tqdm
    - numba

  # version constraints of optional dependencies
  run_constrained:
    - tomophantom >=2
    - astra-toolbox >=1.9.9.dev5
    - tigre >=2.4
    - ccpi-regulariser >=24.0.1
    - olefile >=0.46
    - zenodo_get >=1.6

about:
  home: https://TomographicImaging.github.io/CIL
  license:  Apache 2.0 License
  summary: 'CCPi Core Imaging Library'
