package:
  name: cil
  version: {{ environ.get('GIT_DESCRIBE_TAG','v')[1:] }}

source:
  path: ..

build:
  skip: True # [py==38 and np==115]
  preserve_egg_dir: False
  number: {{ GIT_DESCRIBE_NUMBER }}
  missing_dso_whitelist:
    - /lib64/libc.so.6            # [linux]
    - /lib64/libm.so.6            # [linux]
    - /lib64/libpthread.so.0      # [linux]
    - /lib64/ld-linux-x86-64.so.2 # [linux]

test:
  requires:
    - {{ pin_compatible('numpy', min_pin='x.x', max_pin='x.x') }}
    - python-wget
    - cvxpy              # [ linux and py==37 and np==118 ]
    - scikit-image
    - tomophantom        # [ linux ]
    - cil-astra          # [ linux ] 
    - cil-data >=21.3.0
    - tigre              # [ linux or win ] 
    - numba
    - packaging
    - ccpi-regulariser   # [ not osx ]
    
  source_files:
    - ./Wrappers/Python/test     # [win]
    - ./cil/Wrappers/Python/test # [not win] 

  commands:
    - python -c "import os; print ('TESTING IN THIS DIRECTORY' , os.getcwd())"
    - python -m unittest discover Wrappers/Python/test        # [win]
    - python -m unittest discover -s cil/Wrappers/Python/test # [not win]
    
requirements:
  build:
    - python
    - numpy {{ numpy }}
    - setuptools
    - cmake         # [not osx]
    - cmake >=3.16 # [osx]
    - libgcc-ng     # [linux]
    - libstdcxx-ng  # [linux]
    - _openmp_mutex # [linux]
    - openmp        # [osx]
    - vc 14         # [win]
    - cil-data
    - ripgrep
    - ipp-include
    - ipp-devel
    - ipp

  run:
    - python
    - {{ pin_compatible('numpy', min_pin='x.x', max_pin='x.x') }}
    - scipy
    - matplotlib >=3.3.0
    - h5py
    - pillow
    - libgcc-ng     # [linux]
    - libstdcxx-ng  # [linux]
    - _openmp_mutex # [linux]
    - openmp        # [osx]
    - vc 14         # [win]
    - dxchange
    - olefile >=0.46
    - pywavelets
    - cil-data
    - ipp
    - tqdm
  
about:
  home: http://www.ccpi.ac.uk/cil
  license:  Apache 2.0 License
  summary: 'CCPi Core Imaging Library'
