blank_issues_enabled: false
contact_links:
- name: Discord
  url: https://discord.gg/9NTWu9MEGq
  about: Chat with CIL developers & users
- name: Docs
  url: https://tomographicimaging.github.io/CIL
  about: CIL documentation website
