package:
  name: ccpi-framework
  version: 0.11.0


build:
  preserve_egg_dir: False
#script_env:
#    - CIL_VERSION   
  number: 0
  
requirements:
  build:
    - python
    - numpy
    - setuptools

  run:
    - python
    - numpy
    - scipy
    - matplotlib
  run:
    - python
    - numpy
    - cvxpy
    - scipy
    - matplotlib
	
about:
  home: http://www.ccpi.ac.uk
  license:  Apache 2.0 License
  summary: 'CCPi Framework'
