package:
  name: ccpi-framework
  version: {{ environ['CIL_VERSION'] }}


build:
  preserve_egg_dir: False
  script_env:
    - CIL_VERSION   
#  number: 0
  
requirements:
  build:
    - python
    - numpy
    - setuptools

  run:
    - python
    - numpy
    - matplotlib
  run:
    - python
    - numpy
    - cvxpy
	
about:
  home: http://www.ccpi.ac.uk
  license:  Apache 2.0 License
  summary: 'CCPi Framework'
