name: build
on:
  workflow_dispatch:
  release: {types: [published]}
  push:
    branches: [master]
    tags: ['**']
    paths-ignore:
    - 'CHANGELOG.md'
    - 'CITATION.cff'
    - 'LICENSE'
    - 'scripts/**'
    - 'NOTICE.txt'
    - 'README.md'
  pull_request:
    branches: [master]
    paths-ignore:
    - 'CHANGELOG.md'
    - 'CITATION.cff'
    - 'LICENSE'
    - 'scripts/**'
    - 'NOTICE.txt'
    - 'README.md'
jobs:
  test:
    defaults: {run: {shell: 'bash -el {0}'}}
    runs-on: ${{ matrix.os }}-${{ matrix.os == 'ubuntu' && '24.04' || '2022' }}
    strategy:
      matrix:
        os: [windows]
        python-version: [3.12]
        numpy-version: [1.26]
        tqdm-ref: [e4d9742, a31d97f, fc69588, c682c7b, 17f246b, ef4a142, v4.68.0]
      fail-fast: false
    steps:
    - uses: actions/checkout@v6
      with: {fetch-depth: 0, submodules: recursive}
    - name: set requirements
      run: sed -ri -e 's/(.* python) .*/\1=${{ matrix.python-version }}/' -e 's/(.* numpy) .*/\1=${{ matrix.numpy-version }}/' -e 's/cuda*/py*/' -e '/tigre/d' scripts/cil_development.yml
    - uses: conda-incubator/setup-miniconda@v4
      with:
        miniforge-version: latest
        use-mamba: true
        mamba-version: "*"
        channels: conda-forge
        activate-environment: cil_dev
        environment-file: scripts/cil_development.yml
    - name: pip install .
      run: |
        pip install .
        pip install --no-deps --force-reinstall "git+https://github.com/tqdm/tqdm@${{ matrix.tqdm-ref }}"
    - name: test
      run: python -m unittest discover -v ./Wrappers/Python/test
